version: "3.8"

services:
    landing:
        build: .
        image: revisionary_landing:latest
        container_name: revisionary_landing
        restart: "always"
        # depends_on:
        #     - backend
        # volumes:
        #     - ./landing/src:/landing/src
        # networks:
        #     - backend-network
        # environment:
        #     HOST: 0.0.0.0
        #     PORT: 3000
        networks:
            - proxy-network


networks:
    proxy-network: {}
